version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: calculo_de_inss_development
    ports:
      - "5432:5432"

  testdb:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: calculo_de_inss_test
    ports:
      - "55432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/calculo_de_inss_development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calculo_de_inss_development
      RAILS_ENV: development
    depends_on:
      - db

  test:
    build: .
    command: bash -c "bundle exec rspec"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      DATABASE_URL: postgresql://postgres:password@testdb:5432/calculo_de_inss_test
      POSTGRES_HOST: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calculo_de_inss_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
      RAILS_ENV: test
    depends_on:
      - testdb

volumes:
  postgres_data:
  bundle_cache:
